index:
    path: /
    controller: App\Controller\HomeController::index

productoslistado:
    path: /producto
    controller: App\Controller\ProductoController::index

categorianuevopost:
    path: /categoria/nuevo/{id?}
    controller: App\Controller\CategoriasController::insertupdate

categoriaeditarpost:
    path: /categoria/editar/{id}
    controller: App\Controller\CategoriasController::insertupdate
  
categoriaguardarpost:
    path: /categoria/guardar
    controller: App\Controller\CategoriasController::insertupdatepost
    methods: [POST]
